name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ATTOM_API_KEY: ${{ secrets.ATTOM_API_KEY }}
      ATTOM_API_BASE_URL: https://api.gateway.attomdata.com

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Write .env file
        run: |
          echo "ATTOM_API_KEY=$ATTOM_API_KEY" > .env
          echo "ATTOM_API_BASE_URL=$ATTOM_API_BASE_URL" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Lint Markdown
        run: npx markdownlint-cli2 README.md || true

      - name: Run tests
        run: npm test -- --run
